### PR TITLE
Fix TrainList bug using non-existent Name field

### LINKED ISSUE #48: Delete train.Name from TrainList
Delete train.Name from TrainList...field does not exist.

### PR DESCRIPTION
**Pull request by axelclark**
* Fix TrainList bug using non-existent Name field
* Closes #48

### CODE REVIEW

File: components/TrainList.js [hunk 1]
```diff
@@ -54,6 +53,7 @@ const TrainList = ({ trains }) => {
 
 const styles = StyleSheet.create({
   container: {
+    marginTop: 10
```
Comment (axelclark) [inline components/TrainList.js]: Missing trailing comma.

[Read more about it here.](http://eslint.org/docs/rules/comma-dangle)

**Comment by axelclark** [comment]
Ebert has finished reviewing this Pull Request and has found:

* 1 possible new issue (including those that may have been commented here).

You can see more details about this review at https://ebertapp.io/github/axelclark/metroAppIOS/pulls/49.
